name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - run: npm install
    - name: Build Vue
      run: |
            set -e
            git config --global init.defaultBranch main
            git config --global user.email 'delon.borges@icloud.com'
            git config --global user.name 'Delon Borges'
            npm run build
            cd dist
            echo 'delonborges.com' > CNAME
            git init
            git add -A
            git commit -m 'Deploy'
            git push -f git@github.com:delonborges/delonborges-website.git main:gh-pages
      shell: bash
