name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: delonborges/actions-vue-gh-pages-deploy@1.0.0
      with:
        username: 'delonborges'
        reponame: 'delonborges-website'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        cname: 'delonborges.com'
